### ISSUE TITLE
Immolate re-applies even if there is already on target

### ISSUE THREAD

**Issue by ZvekiSU** [pepopo978/Cursive#14]
/cursive curse Immolate|target

I noticed that Immolate re-applies to the target that already has it.
This happens if it gets re-applied only after the first cast.

**Comment by pepopo978** [comment]
there was a small delay where it would check for resists where it would let you cast again, fixed in latest version.

however it won't work with nampower queuing (saw you made an issue there) as it will check the condition for whether it has the curse while you are still casting.  Need to use QueueScript

**Comment by ZvekiSU** [comment]
/cursive curse Immolate|target

works now without nampower: it does not get re-applied. thanks

--------------

/run QueueScript('SlashCmdList.CURSIVE("curse Soul Fire(Rank 4)|target")SlashCmdList.CURSIVE("curse Immolate(Rank 8)|target")SlashCmdList.CURSIVE("curse Conflagrate(Rank 4)|target")SlashCmdList.CURSIVE("curse Searing Pain(Rank 6)|target")')

this also works perfectly with nampower, however I noticed that Immolate is sometimes still getting re-applied if the macro gets pressed rapidly. perhaps a small delay still present?

--------------

On a sidenote: is it mandatory to put spell ranks, or will it always cast the highest one?

**Comment by pepopo978** [comment]
Don't need to put ranks - default is highest, it uses CastSpellbyName

not entirely sure how you are still getting it to happen I'll look again later

**Comment by pepopo978** [comment]
try latest version, I made it track pending casts should work much better now.  I think even works with queuing

**Comment by ZvekiSU** [comment]
Beautiful. Many thanks!
Great work.
