### ISSUE TITLE
Casting the same type of spell before the timer ends will not overwrite the previous spell.

### ISSUE THREAD

**Issue by jilinge2** [pepopo978/Cursive#4]
When using spell of the same type that cannot coexist, you cannot overwrite the previous spell. The icon and timer of the previous spell will spell be displayed on the frame, causing the replaced spell to be unable to be cast again at this time. For example, Serpent Sting --> Viper Sting --> Serpent Sting, or between different types of curses for a Warlock.

**Comment by pepopo978** [comment]
hmm I tried on warlock with curses and it works fine, the new curse replaces the old, I don't have hunter.

Is this in chinese client?   Check if this curseName / spell name check is the issue
```
Cursive:RegisterEvent("CHAT_MSG_SPELL_AURA_GONE_OTHER", function(message)
	-- check if spell that faded is relevant
	local _, _, spell, target = string.find(message, fades_test)
	if spell and target then
		if curses.trackedCurseNamesToTextures[spell] then
			-- loop through targets with active curses
			for guid, data in pairs(curses.guids) do
				for curseName, curseData in pairs(data) do
					if curseName == spell then                            <-------    this one
						-- see if target still has that curse
						if not curses:ScanGuidForCurse(guid, curseData.spellID) then
							-- remove curse
							curses:RemoveCurse(guid, curseName)
						end
					end
				end
			end
		end
	end
end
```

**Comment by pepopo978** [comment]
these tests need to be localized that's probably the issue

```
local afflict_test = "^(.+) is afflicted by (.+) %((%d+)%)" -- for stacks 2-5 will be "Fire Vulnerability (2)".
local gains_test = "^(.+) gains (.+) %((%d+)%)" -- for stacks 2-5 will be "Fire Vulnerability (2)".
local fades_test = "(.+) fades from (.+)"
local resist_test = "Your (.+) was resisted by (.+)"
```

**Comment by jilinge2** [comment]
I've found the reason, but I'm a newbie and not very familiar with using git to submit code. Could you help me make the changes directly?

**Comment by jilinge2** [comment]
I've found the reason, but I'm a newbie and not very familiar with using git to submit code. Could you help me make the changes directly?
In curses.lua, add:
`local L = AceLibrary("AceLocale-2.2"):new("Cursive")

local fades_test = L["(.+) fades from (.+)"]
local resist_test = L["Your (.+) was resisted by (.+)"]`

In Localization.lua:

For enUS, add:
`["(.+) fades from (.+)"] = true,
["Your (.+) was resisted by (.+)"] = true,`

For zhCN, add:
`["(.+) fades from (.+)"] = "(.+)效果从(.+)身上消失",
["Your (.+) was resisted by (.+)"] = "你的(.+)被(.+)抵抗了",`

**Comment by jilinge2** [comment]
I've found the reason, but I'm a newbie and not very familiar with using git to submit code. Could you help me make the changes directly?
In curses.lua, add:

```
local L = AceLibrary("AceLocale-2.2"):new("Cursive")

local fades_test = L["(.+) fades from (.+)"]
local resist_test = L["Your (.+) was resisted by (.+)"]
```

In Localization.lua:

For enUS, add:
```
["(.+) fades from (.+)"] = true,
["Your (.+) was resisted by (.+)"] = true,
```

For zhCN, add:
```
["(.+) fades from (.+)"] = "(.+)效果从(.+)身上消失",
["Your (.+) was resisted by (.+)"] = "你的(.+)被(.+)抵抗了",
```

**Comment by pepopo978** [comment]
seems like you figured it out :) #7
