### ISSUE TITLE
warlock curses keep applying to the same target

### ISSUE THREAD

**Issue by phyx1u5** [pepopo978/Cursive#9]
using the latest commit 92bc69d6d8cd1a80958aa21b21cb589b10a29c1f

using the following macros:
/cursive multicurse corruption|HIGHEST_HP

and

/cursive multicurse curse of agony|HIGHEST_HP

the curses keep applying to the same targets over and over.
what is expected to happen is they keep cursing new targets.

**Comment by pepopo978** [comment]
It is case sensitive, have to match the spell name in game
```
/cursive multicurse Corruption|HIGHEST_HP
/cursive multicurse Curse of Agony|HIGHEST_HP
```
